version: 2
updates:
- package-ecosystem: gomod
  directory: "/provider"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  reviewers:
  - ringods
- package-ecosystem: gomod
  directory: "/sdk"
  schedule:
    interval: monthly
  open-pull-requests-limit: 3
  reviewers:
  - ringods
